**Soal 1. Data Preparation**

Bacalah Dataset dengan memberikan beberapa argumen sehingga bisa membaca datetime

In [1]:
#code here
import pandas as pd
import numpy as np

df=pd.read_csv('climate_change.csv')
df['date']=pd.to_datetime(df['date'])
df

           date   meantemp    humidity  wind_speed  meanpressure
0    2013-01-01  10.000000   84.500000    0.000000   1015.666667
1    2013-01-02   7.400000   92.000000    2.980000   1017.800000
2    2013-01-03   7.166667   87.000000    4.633333   1018.666667
3    2013-01-04   8.666667   71.333333    1.233333   1017.166667
4    2013-01-05   6.000000   86.833333    3.700000   1016.500000
...         ...        ...         ...         ...           ...
1457 2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458 2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459 2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460 2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461 2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

Expected output:

(Gambar hanya sebagian)

![alt text](https://drive.google.com/uc?id=1TqrXs9JStRXqiF0NIWiMdo5r8CQ-S74-)



---



---

Soal 2. Selection

Tampilkan data keseluruhan untuk tahun 2015 di bulan November

In [2]:
#code here
df_2015=df[(df['date'].dt.year==2015) &(df['date'].dt.month==11)]
df_2015

           date  meantemp  humidity  wind_speed  meanpressure
1034 2015-11-01    22.875    70.500      0.9250      1016.250
1035 2015-11-02    23.375    71.375      0.4625      1015.875
1036 2015-11-03    24.000    67.875      0.4750      1014.250
1037 2015-11-04    23.750    69.000      0.9250      1012.250
1038 2015-11-05    22.125    75.250      5.1000      1012.375
1039 2015-11-06    22.875    74.375      2.3250      1012.750
1040 2015-11-07    21.875    74.875      1.1625      1014.625
1041 2015-11-08    21.875    70.250      1.8625      1015.875
1042 2015-11-09    21.750    73.625      0.7000      1015.000
1043 2015-11-10    22.750    72.625      0.7000      1013.500
1044 2015-11-11    21.875    59.500      4.6375      1014.375
1045 2015-11-12    21.875    60.500      5.7875      1015.375
1046 2015-11-13    22.375    59.375      5.3250      1014.875
1047 2015-11-14    22.375    59.625      3.4750      1012.000
1048 2015-11-15    22.500    62.000      0.0000      1012.000
1049 2015-11-16    21.875    50.375      2.7875      1012.625
1050 2015-11-17    19.875    48.375      5.1000      1013.500
1051 2015-11-18    18.500    57.625      4.4000      1016.375
1052 2015-11-19    18.500    64.750      0.9250      1017.500
1053 2015-11-20    18.500    66.000      0.4625      1016.125
1054 2015-11-21    18.750    67.625      1.3875      1015.500
1055 2015-11-22    18.625    64.875      0.4625      1015.125
1056 2015-11-23    17.000    73.500      0.0000      1015.875
1057 2015-11-24    18.500    63.000      1.6250      1016.000
1058 2015-11-25    19.375    56.375      5.7875      1014.750
1059 2015-11-26    20.000    59.500      0.9250      1012.750
1060 2015-11-27    18.500    66.250      2.5500      1011.250
1061 2015-11-28    18.750    82.125      1.1625      1015.375
1062 2015-11-29    18.125    81.250      1.1625      1018.000
1063 2015-11-30    19.500    82.375      0.9250      1016.750

Expected output:

(Gambar hanya sebagian)

![alt text](https://drive.google.com/uc?id=1ABMLSmdQ817PIdxW1v7rUKelOj_W241g)



---



---

**Soal 3. Filtering**

Tampilkan data perubahan iklim pada 1 bulan terakhir di tahun 2016 dan jawablah pertanyaan berikut:

Berapakah rata-rata temperatur tertinggi?

In [3]:
#code here
df_2016=df[(df['date'].dt.year==2016)&(df['date'].dt.month==12)]
print(df_2016)
mean=df_2016['meantemp'].mean()
print(f"\nRata-rata temperatur tertinggi bulan Desember 2016 adalah {mean:.2f}Â°C")

           date   meantemp   humidity  wind_speed  meanpressure
1430 2016-12-01  19.750000  84.000000    2.704167   1016.875000
1431 2016-12-02  19.208333  75.875000    4.945833   1017.750000
1432 2016-12-03  21.208333  52.166667    5.866667   1019.333333
1433 2016-12-04  18.900000  55.250000    5.666667   1019.700000
1434 2016-12-05  18.636364  56.590909    4.952381   1017.045455
1435 2016-12-06  18.538462  69.923077    2.503846   1017.961538
1436 2016-12-07  18.250000  74.350000    0.925000   1017.421053
1437 2016-12-08  16.900000  73.300000    1.765000   1016.200000
1438 2016-12-09  19.416667  68.125000    1.312500   1013.416667
1439 2016-12-10  16.444444  82.833333    5.355556   1014.000000
1440 2016-12-11  20.041667  69.583333    4.716667   1013.291667
1441 2016-12-12  19.909091  63.863636    3.281818   1014.181818
1442 2016-12-13  19.050000  62.350000    3.430000   1015.100000
1443 2016-12-14  18.555556  58.611111    8.027778   1017.333333
1444 2016-12-15  18.166667  56.625000    9.879167   1016.666667
1445 2016-12-16  15.833333  63.277778    3.916667   1018.777778
1446 2016-12-17  17.500000  63.388889    6.731579   1016.947368
1447 2016-12-18  16.083333  64.541667    6.420833   1018.083333
1448 2016-12-19  17.857143  56.095238   10.414286   1017.428571
1449 2016-12-20  19.800000  48.533333   15.926667   1015.200000
1450 2016-12-21  18.050000  54.300000   19.404762   1015.619048
1451 2016-12-22  17.285714  57.857143    6.180952   1016.142857
1452 2016-12-23  15.550000  74.700000    1.205000   1014.250000
1453 2016-12-24  17.318182  78.636364    5.236364   1011.318182
1454 2016-12-25  14.000000  94.300000    9.085000   1014.350000
1455 2016-12-26  17.142857  74.857143    8.784211   1016.952381
1456 2016-12-27  16.850000  67.550000    8.335000   1017.200000
1457 2016-12-28  17.217391  68.043478    3.547826   1015.565217
1458 2016-12-29  15.238095  87.857143    6.000000   1016.904762
1459 2016-12-30  14.095238  89.666667    6.266667   1017.904762
1460 2016-12-31  15.052632  87.000000    7.325000   1016.100000

Rata-rata temperatur tertinggi bulan Desember 2016 adalah 17.67Â°C

Expected output:

(Gambar hanya sebagian)

![alt text](https://drive.google.com/uc?id=1X2hXsvrRGvqHqtc5BFbVvRXwh5YxBQ_P)

Jawab disini:

Rata-rata temperatur tertinggi 1 bulan terakhir di tahun 2016 adalah 17.67Â°C

---



---

**Soal 4. Time grouping**



*   Lakukan grouping data perubahan iklim pada tahun 2016 berdasarkan frekuensi 1 bulan dengan memberikan agregasi max pada kolom meantemp. humidity, wind_speed dan meanpressure!
*   Berikan analisa, di bulan apa rata-rata temperatur, humidity, wind_speed dan meanpressure tertinggi?

In [4]:
#code here
df['date'] = pd.to_datetime(df['date'])
df.set_index('date', inplace=True)

df_2016 = df.loc['2016']

# grouping
monthly_max = df_2016.resample('ME').max()
print(monthly_max)

#agregasi max
max_meantemp_month = monthly_max['meantemp'].idxmax()
max_humidity_month = monthly_max['humidity'].idxmax()
max_wind_speed_month = monthly_max['wind_speed'].idxmax()
max_meanpressure_month = monthly_max['meanpressure'].idxmax()

print("\nAnalisis:")
print(f"- Temperatur tertinggi di bulan {max_meantemp_month.strftime('%B')} dengan nilai {monthly_max['meantemp'].max():.2f}.")
print(f"- Humidity tertinggi di bulan {max_humidity_month.strftime('%B')} dengan nilai {monthly_max['humidity'].max():.2f}.")
print(f"- Wind speed tertinggi di bulan {max_wind_speed_month.strftime('%B')} dengan nilai {monthly_max['wind_speed'].max():.2f}.")
print(f"- Mean pressure tertinggi di bulan {max_meanpressure_month.strftime('%B')} dengan nilai {monthly_max['meanpressure'].max():.2f}.")

             meantemp   humidity  wind_speed  meanpressure
date
2016-01-31  20.142857  88.833333   11.240000   1021.142857
2016-02-29  23.875000  77.000000   17.137500   1020.071429
2016-03-31  30.000000  67.800000   22.100000   7679.333333
2016-04-30  35.687500  44.250000   19.653846   1009.400000
2016-05-31  38.272727  74.812500   18.425000   1007.466667
2016-06-30  38.200000  75.071429   21.306250   1002.833333
2016-07-31  34.187500  93.875000   13.656250   1004.625000
2016-08-31  33.809524  89.555556   14.666667   1006.200000
2016-09-30  33.444444  87.240000   17.908333   1352.615385
2016-10-31  33.269231  71.875000   15.825000   1017.807692
2016-11-30  25.640000  80.086957   15.085000   1350.296296
2016-12-31  21.208333  94.300000   19.404762   1019.700000

Analisis:
- Temperatur tertinggi di bulan May dengan nilai 38.27.
- Humidity tertinggi di bulan December dengan nilai 94.30.
- Wind speed tertinggi di bulan March dengan nilai 22.10.
- Mean pressure tertinggi di bulan March dengan nilai 7679.33.

Expected output:

(Gambar hanya sebagian)

![alt text](https://drive.google.com/uc?id=1s2Y8Dc3M3xbG-51mTuTmXUFgLvHDvc5Q)

Jawab disini:

Analisis:
- Temperatur tertinggi di bulan May dengan nilai 38.27.
- Humidity tertinggi di bulan December dengan nilai 94.30.
- Wind speed tertinggi di bulan March dengan nilai 22.10.
- Mean pressure tertinggi di bulan March dengan nilai 7679.33.

---



---

**Soal 5. Time Differenced**

Tunjukkanlah perubahan iklim di tahun 2016 pada minggu terakhir

In [7]:
#code here
df = pd.read_csv('climate_change.csv')
df['date'] = pd.to_datetime(df['date'])
df.set_index('date', inplace=True)

last_week_2016 = df.loc['2016-12-26':'2016-12-31']
daily_diff = last_week_2016[['meantemp', 'humidity', 'wind_speed', 'meanpressure']].diff()
print("\nPerubahan  iklim di tahun 2016 pada minggu terakhir: \n")
print(daily_diff)

Perubahan  iklim di tahun 2016 pada minggu terakhir:

            meantemp   humidity  wind_speed  meanpressure
date
2016-12-26       NaN        NaN         NaN           NaN
2016-12-27 -0.292857  -7.307143   -0.449211      0.247619
2016-12-28  0.367391   0.493478   -4.787174     -1.634783
2016-12-29 -1.979296  19.813665    2.452174      1.339545
2016-12-30 -1.142857   1.809524    0.266667      1.000000
2016-12-31  0.957393  -2.666667    1.058333     -1.804762

Expected output:

(Gambar hanya sebagian)

![alt text](https://drive.google.com/uc?id=1miJBQeGMyUS_G3bwP14Plo4s5950oYy5)



---



---